<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="UTF-8">
    <title><?= $welcomeTitle ?> | SaveBlackBoard</title>
    <link rel="icon" href="<?= PATH.'/resources/assets/images/favicon.png'?>" by="https://www.flaticon.com/authors/pixel-buddha"/>
    <meta name="author" content="jeconiass2009@hotmail.com, +55 (84)9 9438-1350"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <meta name="description" content="Uma maneira de salvar e assegurar que todas aquelas fotos tiradas do quadro-negro não sejam perdidas, Save BlackBoard!"/>
    <meta name="URL" content="<?=empty($_SERVER['HTTPS']) ? 'http://'.$_SERVER['SERVER_NAME'] : 'https://' . $_SERVER['SERVER_NAME'];?>"/>
    <meta name="language" content="portuguese"/>
    <meta name="copyright" content="all rights"/>
    <meta name="robots" content="INDEX, FOLLOW"/>
    <meta name="revisit-after" content="3 days"/>
    <meta name="reply-to" content="contato@olamundoweb.com.br"/>
    <meta name="document-rights" content="Public"/>
    <meta name="document-rating" content="General"/>
    <meta name="document-state" content="Dynamic"/>
    <meta http-equiv="Content-Language" content="PT-BR"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <!-- CARREGAR CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= PATH.'/resources/assets/css/animate.css'?>">
    <link rel="stylesheet" href="<?= PATH.'/resources/assets/css/fontawesome-all.min.css'?>">
    <link rel="stylesheet" href="<?= PATH.'/resources/assets/css/login.css'?>">
  </head>
  <body>
    <header class="header-language">
      <ul class="col-md-1 offset-md-11">
        <li class="idiomas-action" id="a"><?= $languages ?></li>
        <div class="toHidden">
          <ul class="list-idiomas">
            <li>
              <a href="<?= PATH.'/pt/login'?>">
                <img src="<?= PATH.'/resources/assets/images/icon-brazil.png'?>">
                <p>PT</p>
              </a>
            </li>
            <li>
              <a href="<?= PATH.'/en/login'?>">
                <img src="<?= PATH.'/resources/assets/images/icon-eua.png'?>">
                <p>EN</p>
              </a>
            </li>
          </ul>
        </div>
      </ul>
    </header>
    <section class="section-form">
      <form id="form_login" method="post">
        <?php
        if (isset($_GET['s']) && $_GET['s'] == 'true') {
          echo '<p style="text-align: center; color: green;">Cadastrado com successo!</p>';
        }elseif (isset($_GET['s']) && $_GET['s'] == 'false') {
          echo '<p style="text-align: center; color: red;">Não foi possível efetuar o cadastro!</p>';
        }elseif (isset($_GET['reset']) && $_GET['reset'] == 'true') {
          echo '<p style="text-align: center; color: green;">Senha alterada!</p>';
        }elseif (isset($_GET['reset']) && $_GET['reset'] == 'false') {
          echo '<p style="text-align: center; color: red;">Não foi possível alterar a senha!</p>';
        }
        ?>
        <h1>Save BlackBoard</h1>
        <input id="email" type="email" name="email" value="<?php if(isset($_COOKIE['turma'])){echo $_COOKIE['turma']; }?>" placeholder="<?= $classEmail ?>" required autocomplete="off">
        <input id="password" type="password" name="senha" value="" maxlength="20" minlength="6" placeholder="<?= $key ?>" required>
        <a href="<?=PATH.'/'.$initial.'/recovery/password'?>" class="a-resetpass"><?= $forgetPass ?></a>
        <button type="submit" class="" name="send"><?= $access ?></button>
        <a href="<?=PATH.'/'.$initial.'/cadastro'?>" class="a-cadastro"><?= $register ?></a>
      </form>
    </section>
    <article class="apresentacao">
      <section class="page01">
        <img src="<?=PATH.'/resources/assets/images/boardblack.png'?>" alt="Quadro-Negro">
        <p><?= $sectionOne ?></p>
      </section>
      <section class="page02">
        <a href="https://github.com/jeconiassantos/saveblackboard" target="_blank">
          <i class="fab fa-github fa-7x"></i>
        </a>
        <p><?= $sectionTwo ?></p>
      </section>
    </article>
  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="<?= PATH.'/resources/assets/js/login.js'?>"></script>
  <script src="<?= PATH.'/resources/assets/js/notify.min.js'?>"></script>
</html>
